name: flow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make setup
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: tests
        run: make test
      - name: lint
        run: make lint


